Issue 1 implement home screen
PreetiRajguru/ConnectorsAssignment pull request #8
Opened 2023-08-11 06:42 UTC by PreetiRajguru

Home Screen Implementation :
- Navbar 
- Sidebar
- Main Screen
- UI Modifications
- Dynamic Cards
- Dropdowns 
- Code Refactoring

2023-08-11 08:18 UTC, RavirajSuryavanshi requested changes
Please work on the feedback

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +// const Configure = () => {
Remove unused code

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +              <label>First Name:</label>
Is the Label text correct or Am I missing something??

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +            <button type="button" className="btn btn-primary mr-2" onClick={handleNext}>
Again I may to wrong but btn & btn-primary will create a button with blue background. If that's true then as per wireframes it should be a link.

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +  const handleSubmit = () => {
We might want to check if the current step is 5?

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +              <label> Last Name:</label>
Is the Label text correct or Am I missing something??
It seems we are referencing it from somewhere but not updating it with the UI label's

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +    dropdown: false
Are we expecting the Healthy link in this object or it's coming from somewhere else. If that's true when will it be a good thought to consider it in this object???

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="grey" className="bi bi-gear-fill settings-headers" viewBox="0 0 16 16" style={{ verticalAlign: 'middle', marginRight: '-
I think we can avoid SVG's being used in the code, let's try to use actual Icons

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +                    <div class="card " style={{ boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)" }}>
Can we avoid using inline CSS? If that's not possible I would have talked to Pankaj to understand if there a way to do it.

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +                          <span>Healthy</span>
It's a hyperlink in my opinion

2023-08-11 08:18 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +          <span className='card-section1'><b>NEW CONNECTORS</b></span>
class name could have been more meaningful

2023-08-11 08:19 UTC, RavirajSuryavanshi commented
Please work on creating the New Connector sections dynamically

2023-08-11 09:04 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +// const Configure = () => {
Removed the code

2023-08-11 09:06 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +              <label>First Name:</label>
Will be implementing the Configure Component in the next Issue

2023-08-11 09:06 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +            <button type="button" className="btn btn-primary mr-2" onClick={handleNext}>
Will be implementing the Configure Component in the next Issue

2023-08-11 09:07 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +  const handleSubmit = () => {
Will be implementing the Configure Component in the next Issue

2023-08-11 09:07 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +              <label> Last Name:</label>
Will be implementing the Configure Component in the next Issue

2023-08-11 09:26 UTC, PreetiRajguru commented on connectors/src/Components/HomePage.js
> +          <span className='card-section1'><b>NEW CONNECTORS</b></span>
Used meaningful classnames

2023-08-11 09:34 UTC, PreetiRajguru commented on connectors/src/Components/HomePage.js
> +                          <span>Healthy</span>
Created link using the anchor tag

2023-08-11 09:50 UTC, PreetiRajguru commented on connectors/src/Components/HomePage.js
> +                    <div class="card " style={{ boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)" }}>
Removed all occurrences of inline css

2023-08-11 10:23 UTC, PreetiRajguru commented on connectors/src/Components/HomePage.js
> +    dropdown: false
Connectors Health Detection
Are like Health Checkpoints 
Related to server and
Database connectivity
It is like a Test Operation that verifies the on-going operations related to connectors .
So basically this should be related separately for each connector and passed through the object itself.
Passed the Hyperlink through the Object.

2023-08-11 11:29 UTC, PreetiRajguru commented on connectors/src/Components/HomePage.js
> +          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="grey" className="bi bi-gear-fill settings-headers" viewBox="0 0 16 16" style={{ verticalAlign: 'middle', marginRight: '-
Replaced all SVG's with Bootstrap Icons

2023-08-12 15:42 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +            <button type="button" className="btn btn-primary mr-2" onClick={handleNext}>
@PreetiRajguru based on the discussion will review this work in future PR's

2023-08-12 15:42 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +  const handleSubmit = () => {
@PreetiRajguru based on the discussion will review this work in future PR's

2023-08-17 06:09 UTC, RavirajSuryavanshi requested changes

2023-08-17 06:09 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +          <span className='card-section1'><b>NEW CONNECTORS</b></span>
@ix-pankajk  Can you please suggest if we can use better naming convention for 'card-section1'?

2023-08-17 06:09 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    text-align: left !important;
We should avoid using Important

2023-08-17 06:09 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    /* width: 230px; */
Remove commented code

2023-08-17 06:09 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    margin-left: 0px
What is the meaning/effect of margin-left 0px? what is the default margin that is getting applied here?

2023-08-17 06:09 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +.Navbar-header {
Follow css standards for declaring class name

2023-08-18 05:32 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +// const Configure = () => {
This file is not supposed to be in this PR hence resolving this comment

2023-08-18 06:15 UTC, PreetiRajguru commented on connectors/src/style.css
> +    text-align: left !important;
Removed Usage of !important in CSS

2023-08-18 06:19 UTC, PreetiRajguru commented on connectors/src/style.css
> +    margin-left: 0px
Removed this CSS class as it was not referenced

2023-08-18 06:19 UTC, PreetiRajguru commented on connectors/src/style.css
> +.Navbar-header {
Renamed the classnames

2023-08-22 06:02 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +          <span className='card-section1'><b>NEW CONNECTORS</b></span>
@PreetiRajguru Am I still missing something? Please help me if there is a understanding gap.

I took the latest pull of Issue-1_implement_home_screen branch locally but I still see these. Something is wrong I assume.

![image](https://github.com/PreetiRajguru/ConnectorsAssignment/assets/37995199/aa5e388f-fcb7-4d43-a137-d0454950442c)

2023-08-22 06:03 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    margin-left: 0px
@PreetiRajguru  It's fine if you have removed it as this was not referenced, But I would like to learn some basics of css so if you can answer this it would be a great thing.

2023-08-22 06:26 UTC, RavirajSuryavanshi commented on connectors/src/Components/HomePage.js
> +          <span className='card-section1'><b>NEW CONNECTORS</b></span>
As discussed somehow this still does not reflect on my version. But I trust that you have done that

2023-08-22 06:27 UTC, RavirajSuryavanshi commented
Merging the PR as all the PR Comments are resolved

2023-08-22 06:27 UTC, merged