Issue 2 -  General Details Screen
PreetiRajguru/ConnectorsAssignment pull request #9
Opened 2023-08-16 17:43 UTC by PreetiRajguru

- Implemented Stepper 
- Created General Details Component
- Added Dynamic Data to the Component (Data, Links)
- Added Form Validations (1.Validation on Empty Input, 2.Validation on Next Button)
- Css Enhancements (Conditional Rendering)
- Lifted General Details Component State up to another Component to handle Validations

2023-08-17 06:25 UTC, RavirajSuryavanshi requested changes

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +    return "✓";
Can this be moved to Assets? if this is a icon/img?

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +    { label: 'Sync & Mappings', component: SyncMappings },
Incorrect component rendering. GenralDetails & ConnectAccount component are rendered twice, I understand that this is just for testing purpose but it should removed while creating the PR

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +function Stepper({ current, steps }) {
Not sure what is the standard way of declaring the function name but either of `Stepper` or 'renderStep' is incorrect

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +                <button type="button" className={saveAndFinishClass}>Save & Finish</button>
I believe this could have been a link

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/GeneralDetails.js
> +        link1: '#',
What is link1, link2?

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/GeneralDetails.js
> +                        <br /><br />
We should avoid <br>

2023-08-17 06:25 UTC, RavirajSuryavanshi commented on connectors/src/Components/Sidebar.js
> +        <ul className='sidebar-list'>
These menu's could have been rendered dynamically. Imagine if we have to reduce these menu's

2023-08-18 07:00 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +    { label: 'Sync & Mappings', component: SyncMappings },
Used GeneralDetails Component for rendering . Removed the use of ConnectAccount and SyncMappings.

2023-08-18 07:11 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +function Stepper({ current, steps }) {
All these are Functional Components used for implementing Stepper so they follow Pascal Case Name Convention.
Changed 'renderStep' to 'RenderStep'.

2023-08-18 07:22 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +    return "✓";
Added Bootstrap Icon

2023-08-18 07:29 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +                <button type="button" className={saveAndFinishClass}>Save & Finish</button>
Added <Link>

2023-08-18 07:32 UTC, PreetiRajguru commented on connectors/src/Components/GeneralDetails.js
> +        link1: '#',
Added Meaningful Names to the Links

2023-08-18 08:53 UTC, PreetiRajguru commented on connectors/src/Components/GeneralDetails.js
> +                        <br /><br />
Removed Usage of Br Tags

2023-08-18 09:45 UTC, PreetiRajguru commented on connectors/src/Components/Sidebar.js
> +        <ul className='sidebar-list'>
Sidebar component made Dynamic

2023-08-22 07:33 UTC, RavirajSuryavanshi requested changes

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +        <>
What is the use of <> ?? Something new with react syntax??

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +    const saveAndFinishClass = isStep1 ? 'btn btn-link save-and-finish-button' : 'btn btn-link save-and-finish-button2';
Please find a better way to apply conditional styling

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/Components/Configure.js
> +            setValidationErrors({ generalDetails: "Name is required." });
Error messages should not be hardcoded

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/Components/Navbar.js
> +
Too many line spaces. Please take of this we should not be discussing on this multiple times.

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/Components/Navbar.js
> +
Too many line spaces. Please take of this we should not be discussing on this multiple times.

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    /* position: absolute; */
Remove commented code. Please take of this we should not be discussing on this multiple times.

2023-08-22 07:33 UTC, RavirajSuryavanshi commented on connectors/src/style.css
> +    text-decoration: none !important
Important Why??

2023-08-22 08:45 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +        <>
- <> are called "Fragments." 
-Used to group multiple child elements
- Can be replaced with extra <div>

2023-08-22 08:48 UTC, PreetiRajguru commented on connectors/src/Components/Navbar.js
> +
Removed Extra Spaces.

2023-08-22 08:48 UTC, PreetiRajguru commented on connectors/src/Components/Navbar.js
> +
Removed Extra Spaces.

2023-08-22 08:50 UTC, PreetiRajguru commented on connectors/src/style.css
> +    /* position: absolute; */
Removed all Commented Code

2023-08-22 09:19 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +            setValidationErrors({ generalDetails: "Name is required." });
Added ConstantMessages.js file.

2023-08-22 09:32 UTC, PreetiRajguru commented on connectors/src/Components/Configure.js
> +    const saveAndFinishClass = isStep1 ? 'btn btn-link save-and-finish-button' : 'btn btn-link save-and-finish-button2';
Added Inline Conditional Rendering of  CSS and removed the usage of an extra variable for the same.

2023-08-22 09:32 UTC, PreetiRajguru commented on connectors/src/style.css
> +    text-decoration: none !important
Removed Usage of !important

2023-08-22 10:59 UTC, merged

2023-08-22 10:59 UTC, RavirajSuryavanshi commented
Merging PR as all comments have been resolved.